serlo/database-layer

src/event/model/checkout_revision.rs
src/event/model/create_comment.rs
src/event/model/create_entity.rs
src/event/model/create_entity_link.rs
src/event/model/create_entity_revision.rs
src/event/model/create_taxonomy_link.rs
src/event/model/create_taxonomy_term.rs
src/event/model/create_thread.rs
src/event/model/event.rs
src/event/model/mod.rs
src/event/model/reject_revision.rs
src/event/model/remove_entity_link.rs
src/event/model/remove_taxonomy_link.rs
src/event/model/set_license.rs
src/event/model/set_license_event.rs
src/event/model/set_taxonomy_parent.rs
src/event/model/set_taxonomy_term.rs
src/event/model/set_thread_state.rs
src/event/model/set_uuid_state.rs
src/event/model/unsupported.rs

Adds some further improvement ideas for #28.

refactor /event: further ideas

---

src/event/model/set_uuid_state.rs
src/uuid/model/uuid.rs
src/uuid/routes.rs

event(set_uuid_state): remove instance from request

---

src/event/model/set_uuid_state.rs
src/uuid/model/uuid.rs

tests: fix deadlock

---

.github/workflows/pacts.yml
sqlx-data.json
src/event/model/create_thread.rs
src/threads/model.rs
src/threads/routes.rs

(closes #49, based on #61)
… ups. Both endpoints should probably return `Comment`.

POST /thread/start-thread

---

src/subscription/model.rs

(for https://github.com/serlo/api.serlo.org/issues/231)

add send_email to SubscriptionByUser

---

src/uuid/messages.rs
src/uuid/model/entity/mod.rs

Return null for solutions of math-puzzle Closes #77

Math puzzle return null

---

sqlx-data.json
src/event/model/abstract_event.rs
src/event/model/create_comment.rs
src/event/model/create_thread.rs
src/event/model/event.rs
src/event/model/revision.rs
src/event/model/set_thread_state.rs
src/event/model/set_uuid_state.rs
src/message.rs
src/uuid/model/entity/messages.rs
src/uuid/model/entity/mod.rs

Revision mutations

---

sqlx-data.json
src/uuid/model/entity/mod.rs

closes #102 
Note to self: When this is merged we can remove 1-2 lines in the frontend.

Checkout revision: also set `trashed: false`

---

sqlx-data.json
src/thread/model.rs

Closes https://github.com/serlo/api.serlo.org/issues/387

create-thread: Fix SQL command to get id and instance of taxonomy term

---

Cargo.lock
Cargo.toml
sqlx-data.json
src/notification/model.rs

Closes #105 (Follow-Ups in separate issue)

Omit notifications for unsupported uuids

---

Cargo.lock
Cargo.toml
sqlx-data.json
src/subscription/model.rs

Closes https://github.com/serlo/api.serlo.org/issues/429

getSubscriptions shall only return supported uuids

---

sqlx-data.json
src/message.rs
src/user/messages.rs
src/user/mod.rs
src/user/model.rs
tests/user.rs

For https://github.com/serlo/frontend/issues/935

Add "UserActivityByTypeQuery"

---

.github/wait-for-mysql.sh
.github/wait-for-server.sh
README.md
package.json
scripts/pacts.sh
scripts/run_all_checks.sh
yarn.lock

Hopefully I will open less PRs with errors in the future :smile: :see_no_evil: -> I want to have this in the codebase to make the live for other developers easier.

Add helper script to run all check (for example before pushing)

---

sqlx-data.json
src/event/messages.rs
src/event/mod.rs
src/event/model/event.rs
src/lib.rs
tests/events.rs

@inyono I want to go through this PR tomorrow. There might be some small changes I will do. However it's good enough to get some first feedback :smile:

Add EventsQuery

---

Cargo.lock
Cargo.toml
sqlx-data.json
src/event/model/entity_link.rs
src/event/model/revision.rs
src/event/model/set_uuid_state.rs
src/instance.rs
src/notification/model.rs

Closes https://github.com/serlo/serlo.org-database-layer/issues/107

Follow up for PR with omiting unsupported notifications

---

src/event/model/create_comment.rs
src/thread/model.rs

Fix: A CreateThreadEvent needs to be created in start_thread()

---

Cargo.lock
sqlx-data.json
src/thread/messages.rs
src/thread/model.rs
tests/thread.rs

Closes https://github.com/serlo/serlo.org-database-layer/issues/126
@elbotho @inyono How is first can make the review :smile:

Allow creating threads on user (needed for an MVP)

---

Cargo.lock
sqlx-data.json
src/notification/model.rs

Closes https://github.com/serlo/serlo.org/issues/654

Do not return notifications for unsupported uuids

---

CHANGELOG.md
package.json
scripts/changelog.ts
yarn.lock

add CHANGELOG workflow

---

src/user/messages.rs
src/user/model.rs
tests/user.rs

See https://github.com/serlo/api.serlo.org/issues/459

Rename ActivityByType -> UserActivityByType

---

server/src/metadata/model.rs
server/tests/metadata.rs

Change metadata so that it fulfills
* https://dini-ag-kim.github.io/amb/draft/#inlanguage
* https://dini-ag-kim.github.io/amb/draft/#publisher

Update metadata api

---

CHANGELOG.md
Cargo.lock
scripts/changelog.ts
server/Cargo.toml
server/src/license/model.rs
server/src/user/messages.rs
server/src/user/model.rs
server/tests/user.rs
sqlx-data.json
test-utils/src/lib.rs
yarn.lock

Include fixes for breaking pact tests:
* LicenseQuery shall return 404 when license cannot be found
* UserSetEmailQuery shall also return username
(There is still something broken, however it should be with the code in api / I'll have a look tomorrow)

Fix for pacts

---

server/src/uuid/model/entity/messages.rs
server/src/uuid/model/page/messages.rs
server/src/uuid/model/page/mod.rs
server/tests/entity.rs
server/tests/page.rs
sqlx-data.json

And some changes related to entity/page revision.

Add PageCreateMutation

---

server/src/thread/messages.rs
server/src/thread/model.rs
server/tests/thread.rs

Refactor /server/src/thread

---

server/src/thread/messages.rs
server/src/thread/model.rs
server/tests/thread.rs
sqlx-data.json

for https://github.com/serlo/api.serlo.org/issues/534

Add AllThreadsQuery

---

server/src/uuid/model/entity/mod.rs
server/tests/entity.rs
sqlx-data.json
test-utils/Cargo.toml
test-utils/src/lib.rs

- Fix handling of needsReview See https://github.com/serlo/api.serlo.org/issues/595
- Fix order of children of entities

Fixes: EntityCreateMutation

---

server/src/uuid/model/entity/mod.rs
server/tests/entity.rs

Fixes https://github.com/serlo/serlo.org-database-layer/issues/229

Fix autoreview entity create

---

server/src/event/model/entity_link.rs
server/src/notification/model.rs
server/src/uuid/model/entity/messages.rs
server/src/uuid/model/entity/mod.rs
server/src/uuid/model/taxonomy_term/mod.rs
server/tests/entity.rs
sqlx-data.json

See https://github.com/serlo/api.serlo.org/issues/609

refactor(entity-create)!: Remove "instance" from payload

---

server/tests/entity.rs
server/tests/events.rs
server/tests/metadata.rs
server/tests/taxonomy_term.rs
server/tests/thread.rs
server/tests/user.rs
server/tests/uuid.rs
test-utils/src/lib.rs

test: Do not check reason text on bad requests

---

server/src/event/messages.rs
server/src/event/mod.rs
server/src/event/model/event.rs

Refactor event messages

---

server/src/event/model/event.rs
server/src/notification/messages.rs
server/src/notification/model.rs

refactor: Submodularize notification messages

---

server/src/uuid/model/entity/messages.rs
server/src/uuid/model/entity/mod.rs

Refactor entity

---

server/tests/entity.rs
server/tests/events.rs
server/tests/metadata.rs
server/tests/navigation.rs
server/tests/page.rs
server/tests/subject.rs
server/tests/taxonomy_term.rs
server/tests/thread.rs
server/tests/user.rs
server/tests/uuid.rs
test-utils/src/lib.rs

Fixes https://github.com/serlo/serlo.org-database-layer/issues/255

Use "should_be" helper functions in test

---

server/tests/entity.rs
server/tests/events.rs
server/tests/metadata.rs
server/tests/navigation.rs
server/tests/page.rs
server/tests/subject.rs
server/tests/taxonomy_term.rs
server/tests/thread.rs
server/tests/user.rs
server/tests/uuid.rs
test-utils/src/lib.rs

Fixes https://github.com/serlo/serlo.org-database-layer/issues/262

Refactor: Reduce number of awaits in tests

---

server/src/uuid/model/entity/mod.rs
server/tests/entity.rs
sqlx-data.json

Fix DeletedEntitiesQuery order

---

scripts/mysql-dump.ts
server/tests/entity.rs
server/tests/events.rs

I moved the change of the UuidSetStateMutation into the DB dump via `yarn mysql:dump`.

fix: Test for DeletedEntitiesQuery

---

Cargo.lock
scripts/changelog.ts
server/Cargo.toml
server/src/uuid/model/entity/mod.rs
server/src/uuid/model/entity_revision/abstract_entity_revision.rs
server/tests/entity.rs

Closes https://github.com/serlo/serlo.org-database-layer/issues/271

fix: Do not add new revision when only "cohesive" is added

---

CHANGELOG.md
scripts/changelog.ts
server/src/uuid/model/taxonomy_term/mod.rs
server/tests/taxonomy_term.rs

feat: TaxonomyTermSortMutation shall support subset of children ids

---

server/src/uuid/model/taxonomy_term/mod.rs
server/tests/taxonomy_term.rs
sqlx-data.json

Exercises cannot only be linked to folders and non exercises to topic folders

---

CHANGELOG.md
Cargo.lock
scripts/changelog.ts
server/Cargo.toml
server/src/uuid/model/entity/messages.rs
server/src/uuid/model/entity/mod.rs
server/src/uuid/model/taxonomy_term/mod.rs
server/tests/entity.rs
server/tests/taxonomy_term.rs
sqlx-data.json

Add EntitySortMutation

---

CHANGELOG.md
Cargo.lock
scripts/changelog.ts
server/Cargo.toml
server/src/thread/messages.rs
server/src/thread/model.rs
server/tests/thread.rs
sqlx-data.json

See https://github.com/serlo/api.serlo.org/issues/676

AllThreadsQuery: filter by instance

---

server/src/thread/model.rs
server/tests/thread.rs
sqlx-data.json

fix: Ignore user threads in AllThreadsQuery

---

CHANGELOG.md
Cargo.lock
scripts/changelog.ts
scripts/generate_changelog_entry.sh
server/Cargo.toml
server/src/uuid/model/entity_revision/abstract_entity_revision.rs
server/src/uuid/model/taxonomy_term/mod.rs
server/tests/taxonomy_term.rs
sqlx-data.json

Similar to the behavior of entities.

fix: Put newly created Taxonomy Terms into the last position in relation to its siblings

---

server/src/user/model.rs
server/tests/user.rs

fix: Do not accept user description which are too long

---

.github/ISSUE_TEMPLATE/refactor-request.md
CHANGELOG.md
Cargo.lock
scripts/changelog.ts
scripts/generate_changelog_entry.sh
server/Cargo.toml
server/src/thread/messages.rs
server/src/thread/model.rs
server/tests/thread.rs
sqlx-data.json

See https://serlo.slack.com/archives/C0BMSC431/p1666617395168269

feat: Order AllThreadsQuery according to last updated

---

CHANGELOG.md
Cargo.lock
scripts/changelog.ts
server/Cargo.toml
server/src/datetime.rs
server/src/thread/messages.rs
server/src/thread/model.rs
server/src/uuid/model/entity/mod.rs
server/tests/thread.rs
sqlx-data.json

If ok, let me version it and merge.

fix: Fix sorting of threads in discussions

---

CHANGELOG.md
Cargo.lock
scripts/changelog.ts
server/Cargo.toml
server/src/uuid/model/taxonomy_term/mod.rs
sqlx-data.json

See https://serlo.slack.com/archives/C9B8ALC78/p1677779384768369

fix: Make all taxonomies below /106081 subjects

---

Cargo.lock
server/tests/entity.rs
server/tests/events.rs
server/tests/metadata.rs
server/tests/page.rs
server/tests/taxonomy_term.rs
server/tests/thread.rs
server/tests/user.rs
server/tests/uuid.rs
test-utils/Cargo.toml
test-utils/src/lib.rs

Add
[`pretty_assertions`](https://docs.rs/pretty_assertions/latest/pretty_assertions) so that we get better diffs in the tests

test: Add `pretty_assertions`

---

server/src/metadata.rs
server/tests/metadata.rs

Fixes #168 
This PR contains only the code -> I want to check with the author unit the values anyways (https://github.com/serlo/database-layer/issues/396) -> So only code checking is needed :smile:

feat(metadata): Update `learningResourceType`

---

server/src/metadata.rs
server/tests/metadata.rs
sqlx-data.json

feat(metadata): Compute a better name for exercises 

---

server/src/metadata.rs
server/tests/metadata.rs

fix(metadata): comply to amb regarding field description

---

server/src/metadata.rs
server/tests/metadata.rs

Implement suggestion from author units

feat(metadata): Update default name

---

server/src/metadata.rs
server/tests/metadata.rs

In case we would like to add additional information for the version, with this change we can do it without any breaking changes.

feat(metadata): Return dict for version

---

server/src/metadata.rs
server/tests/metadata.rs

Fixes https://github.com/serlo/private-issues-sso-metadata-wallet/issues/46 
I think some tests will fail but let's see what the CI has to say. My local environment seems a little bit broken :cry:

Iterate with Olaf on `learningResourceType`

---

scripts/mysql-import-anonymous-data.ts

fix: Set local_infile in mysql

---

.github/workflows/checks.yml
.github/workflows/docker.yml

Fixes https://github.com/serlo/database-layer/issues/463 
---
From what I could see, the versions of the actions did not need to get updated, and only refactored the [Docker](https://github.com/serlo/database-layer/actions/workflows/docker.yml) workflow.
ℹ️ Currently [Docker](https://github.com/serlo/database-layer/actions/workflows/docker.yml)  is not a required check, but it would be nice to add it as a [required check](https://github.com/serlo/database-layer/settings) as part of this change.

chore(deps): Update and refactor GitHub Actions

---

server/src/metadata.rs
server/tests/metadata.rs

This feature was request by a partner who uses our metadata API.

feat(metadata): Add "type" to "mainEntityOfPage"

---

Dockerfile

Revert https://github.com/serlo/database-layer/pull/512

Update Dockerfile: Downgrade rust

---

Cargo.lock
server/Cargo.toml
server/src/alias/messages.rs
server/src/event/messages.rs
server/src/message.rs
server/src/metadata.rs
server/src/navigation/messages.rs
server/src/notification/messages.rs
server/src/operation.rs
server/src/subject.rs
server/src/subscription/messages.rs
server/src/thread/messages.rs
server/src/user/messages.rs
server/src/uuid/messages.rs
server/src/uuid/model/entity/messages.rs
server/src/uuid/model/page/messages.rs
server/src/uuid/model/taxonomy_term/messages.rs
server/src/vocabulary/messages.rs

There is a lot of repetitive match stuff that would be nice to throw out.

Remove some boilerplate

---

server/src/metadata.rs
server/tests/metadata.rs

See https://github.com/dini-ag-kim/amb/issues/218#issuecomment-1669265114

feat: Change "WebAPI" to "WebContent"

---

server/src/metadata.rs
server/tests/metadata.rs

feat: Add new learning resource type of WLO

---

.sqlx/query-0775fb20c50e22a43297a12e8959dc4e6c7527a64d40dfbe885f616acf252865.json
.sqlx/query-0eca65d1eb3fe8686ef46df2f9fad9cfb0fa44f786d09043609fb1a6a411fbf5.json
.sqlx/query-436603084c0bc754c6d6baa29d1eb0d64f1ee26047a4b905585949e5ea544b15.json
.sqlx/query-6b867595e8308dd97239e5dcba9b9bc26453fac7aaecbc238e00a16a0a32bcc5.json
.sqlx/query-86d9154ff359e925b1f73ba4be620d309230f7d3f37c4d710f25f5acffd2527b.json
.sqlx/query-9a3e1b4cb8f99c74056a2f2a6b7bdc276fe171a9059318c92cbf8536e83e45d0.json
.sqlx/query-d4c1b33938809466906554f5bc60faadae4d6e5781bb9acc02f47c7385960e3a.json
.sqlx/query-fc0ca0f5bbca56646e9a9cbad7d897b684ca6301e1c63c108d1497592ef3f34b.json
docker-compose.yml
server/src/uuid/model/comment.rs

Depends on https://github.com/serlo/db-migrations/pull/129

feat: Add "status" to comments

---

server/src/metadata.rs
server/tests/metadata.rs

resolves https://github.com/serlo/backlog/issues/283

test(metadata): update learning resource type assertions

---

README.md
scripts/mysql/mysql-import-anonymous-data.ts

fixes a regression of #604
follow up: If this is accepted we should do the same in https://github.com/serlo/db-migrations/blob/main/scripts/mysql/mysql-import-anonymous-data.ts and maybe other repos as well

fix(import script): fix bug, improve error handling

---

.github/actions/setup-rust/action.yml
.tool-versions
Dockerfile
server/src/lib.rs
server/src/uuid/model/entity/mod.rs
server/src/uuid/model/mod.rs
server/src/uuid/model/page/mod.rs
server/src/uuid/model/taxonomy_term/mod.rs

Upgrade Rust version to 1.74

---

server/src/notification/model.rs
server/src/subscription/model.rs

We will remove them in a DB migration.

test: Remove tests for unsupported uuids

---

server/src/notification/model.rs

test: Fix tests for notifications

---

docker-compose.yml

See https://docs.docker.com/compose/compose-file/04-version-and-name/

chore(docker-compose): Remove "version" tag
